### ISSUE TITLE
/wagmi-core.cjs.dev.js:268 SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by sgalvagno** [thirdweb-example/next-with-typescript#1]
Hi,
I used the template to generate my project

I did the
npm install
npm run dev

and I got the error

zsh> npm run dev

> next-typescript-starter@0.1.0 dev ~/Training/next-typescript
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 1342 ms (854 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 168 ms (855 modules)
~/Training/nft-drop/node_modules/wagmi-core/dist/wagmi-core.cjs.dev.js:268
      options: config?.options
                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (~/Training/nft-drop/node_modules/wagmi-core/dist/wagmi-core.cjs.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 131 ms (858 modules)
~/Training/nft-drop/node_modules/wagmi-core/dist/wagmi-core.cjs.dev.js:268
      options: config?.options
                      ^

**Comment by phellipe5k** [comment]
same error...

**Comment by jarrodwatts** [comment]
Can you confirm this is resolved now?
